trigger: none
pr: none
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client-patch.yml
  parameters:
    SkipAggregateReports: true
    artifacts:
    - name: azure-security-attestation
      groupId: com.azure
      safeName: azuresecurityattestation
      ServiceDirectory: attestation
    - name: azure-security-keyvault-administration
      groupId: com.azure
      safeName: azuresecuritykeyvaultadministration
      ServiceDirectory: keyvault
    - name: azure-security-keyvault-certificates
      groupId: com.azure
      safeName: azuresecuritykeyvaultcertificates
      ServiceDirectory: keyvault
    - name: azure-security-keyvault-keys
      groupId: com.azure
      safeName: azuresecuritykeyvaultkeys
      ServiceDirectory: keyvault
    - name: azure-security-keyvault-secrets
      groupId: com.azure
      safeName: azuresecuritykeyvaultsecrets
      ServiceDirectory: keyvault

